version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: cactus-client-project
    ports:
      - 3306:3306
    volumes:
      - ./data:/data/cactus-client-project